### Use are your own risk, has not been tested by staff. 

---
version: "3"

networks:
  traefik_network:
    external:
      name: web

services:
  dockyard:
    image: khulnasoft/dockyard:devel
    restart: unless-stopped
    networks:
      - traefik_network
    environment:
      - PUID=1000
      - PGID=1000
      - "SECRET_KEY=my_secret_key"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./config:/config
    labels:
      - "traefik.http.services.dockyard.loadbalancer.server.scheme=http"
      - "traefik.http.services.dockyard.loadbalancer.server.port=8000"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.dockyard-http.service=dockyard"
      - "traefik.http.routers.dockyard-http.rule=Host(`dockyard.domain.tld`)"
      - "traefik.http.routers.dockyard-http.entrypoints=http"
      - "traefik.http.routers.dockyard.service=dockyard"
      - "traefik.http.routers.dockyard.rule=Host(`dockyard.domain.tld`)"
      - "traefik.http.routers.dockyard.entrypoints=https"
      - "traefik.http.routers.dockyard.tls=true"
      - "traefik.http.routers.dockyard.tls.certresolver=dns"
      - "traefik.http.routers.dockyard.tls.domains[0].main=domain.tld"
      - "traefik.http.routers.dockyard.tls.domains[0].sans=*.domain.tld"